Analysis of the results of the EMIP dataset

In [1]:
import sys
sys.path.append("..")
import os
import pandas as pd
from numpy import var, mean, sqrt
from pandas import Series
from scipy.stats import spearmanr
from scipy.stats import mannwhitneyu

from utils.ogama import import_data_into_ogama_emip, calculate_results_for_subject_emip, drop_all_subject_tables_emip
from utils.pygazehelper.pygaze import fixation_data_analysis, saccade_data_analysis

Data of Original Results

In [2]:
# Load the original results
participants_metadata = pd.read_csv('../data/StudyEMIP/emip_metadata.csv')
# Remove rows where experiment_language is not 'Java'
participants_metadata = participants_metadata[participants_metadata.experiment_language == 'Java']

PyGaze Analysis

In [3]:
# Run the fixation/saccade algorithm of PyGazeAnalyzer
fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset.csv")
saccade_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_saccades_emip_dataset.csv")

Fixation information saved to results/pygaze_fixations_emip_dataset.csv
Saccade information saved to results/pygaze_saccades_emip_dataset.csv

In [4]:
# Run the fixation/saccade algorithm of PyGazeAnalyzer with different parameters
# For different parameters

fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_lower_maxdist1.csv", {'missing': 0.0, 'maxdist': 15, 'mindur': 50})
fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_lower_maxdist2.csv", {'missing': 0.0, 'maxdist': 10, 'mindur': 50})

fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_higher_maxdist1.csv", {'missing': 0.0, 'maxdist': 35, 'mindur': 50})
fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_higher_maxdist2.csv", {'missing': 0.0, 'maxdist': 50, 'mindur': 50})


fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_lower_mindur1.csv", {'missing': 0.0, 'maxdist': 25, 'mindur': 35})	
fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_lower_mindur2.csv", {'missing': 0.0, 'maxdist': 25, 'mindur': 20})

fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_higher_mindur1.csv", {'missing': 0.0, 'maxdist': 25, 'mindur': 65})
fixation_data_analysis('../data/StudyEMIP/rawdata/', "results/pygaze_fixations_emip_dataset_higher_mindur2.csv", {'missing': 0.0, 'maxdist': 25, 'mindur': 80})

Fixation information saved to results/pygaze_fixations_emip_dataset_lower_maxdist1.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_lower_maxdist2.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_higher_maxdist1.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_higher_maxdist2.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_lower_mindur1.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_lower_mindur2.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_higher_mindur1.csv
Fixation information saved to results/pygaze_fixations_emip_dataset_higher_mindur2.csv

In [5]:
# We load the PyGazeAnalyzer fixation results
pygaze_fixations = pd.read_csv('results/pygaze_fixations_emip_dataset.csv')

# Drop all colums where the task contains 'mupliple_choice'
pygaze_fixations = pygaze_fixations[~pygaze_fixations['Task'].str.contains('mupliple_choice')]

# We combine the two dataframes into one by combining the columns where the values of Participant are the same
results_pygaze = pd.merge(participants_metadata, pygaze_fixations, how='inner', left_on=['id'], right_on=['Participant'])
results_pygaze

,id,age,gender,mother_tongue,english_level,visual_aid,makeup,experiment_language,expertise_experiment_language,time_experiment_language,...,stimulus_vehicle,mother_tongue_original,time_experiment_language_original,time_programming_original,other_languages_original,Participant,Task,Fixation Count,Total Fixation Duration [ms],Average Fixation Duration [ms]
0,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,vehicle_java.jpg,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,1,vehicle_java.jpg,247,33581.623,135.957988
1,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,vehicle_java.jpg,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,1,rectangle_java.jpg,67,6502.875,97.057836
2,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,vehicle_java2.jpg,Slovak,2,5,"c++(low), php(medium), delphi(low)",2,rectangle_java2.jpg,131,12446.719,95.013122
3,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,vehicle_java2.jpg,Slovak,2,5,"c++(low), php(medium), delphi(low)",2,vehicle_java2.jpg,221,18234.353,82.508385
4,3,27,female,Hebrew,high,no,no,Java,none,0.0,...,vehicle_java2.jpg,Hebrew,0,0,c# (low),3,vehicle_java2.jpg,189,31025.879,164.158090
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,214,21,male,Slovak,high,no,no,Java,medium,1.0,...,vehicle_java2.jpg,Slovak,1,4,"C (medium) , JavaScript (medium)",214,vehicle_java2.jpg,561,88332.082,157.454692
410,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,vehicle_java2.jpg,slovak,1,2,C (medium) c# (medium) Java (medium),215,vehicle_java2.jpg,341,55915.682,163.975607
411,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,vehicle_java2.jpg,slovak,1,2,C (medium) c# (medium) Java (medium),215,rectangle_java2.jpg,219,36273.723,165.633438
412,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,vehicle_java2.jpg,Thai,6 weeks,6 weeks,Low,216,vehicle_java2.jpg,296,29761.160,100.544459
413,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,vehicle_java2.jpg,Thai,6 weeks,6 weeks,Low,216,rectangle_java2.jpg,150,13818.919,92.126127

In [6]:
# We load the PyGazeAnalyzer saccade results
pygaze_saccades = pd.read_csv('results/pygaze_saccades_emip_dataset.csv')

# Drop all colums where the task contains 'mupliple_choice'
pygaze_saccades = pygaze_saccades[~pygaze_saccades['Task'].str.contains('mupliple_choice')]

# We combine the two dataframes into one by combining the columns where the values of Participant are the same
results_pygaze_saccades = pd.merge(participants_metadata, pygaze_saccades, how='inner', left_on=['id'], right_on=['Participant'])
results_pygaze_saccades

,id,age,gender,mother_tongue,english_level,visual_aid,makeup,experiment_language,expertise_experiment_language,time_experiment_language,...,mother_tongue_original,time_experiment_language_original,time_programming_original,other_languages_original,Participant,Task,Saccade Count,Total Saccade Duration [ms],Average Saccade Duration [ms],Average Saccade Distance [px]
0,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,1,vehicle_java.jpg,76,74215.197,976.515750,134.748075
1,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,1,rectangle_java.jpg,17,27547.014,1620.412588,124.579446
2,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,Slovak,2,5,"c++(low), php(medium), delphi(low)",2,rectangle_java2.jpg,5,16226.784,3245.356800,144.592684
3,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,Slovak,2,5,"c++(low), php(medium), delphi(low)",2,vehicle_java2.jpg,1,32869.806,32869.806000,384.500895
4,3,27,female,Hebrew,high,no,no,Java,none,0.0,...,Hebrew,0,0,c# (low),3,vehicle_java2.jpg,82,38536.702,469.959780,94.716505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,214,21,male,Slovak,high,no,no,Java,medium,1.0,...,Slovak,1,4,"C (medium) , JavaScript (medium)",214,vehicle_java2.jpg,284,104300.867,367.256574,99.464269
410,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,slovak,1,2,C (medium) c# (medium) Java (medium),215,vehicle_java2.jpg,119,67067.450,563.592017,146.948980
411,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,slovak,1,2,C (medium) c# (medium) Java (medium),215,rectangle_java2.jpg,73,44376.894,607.902658,104.747459
412,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,Thai,6 weeks,6 weeks,Low,216,vehicle_java2.jpg,33,68278.123,2069.034030,172.396854
413,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,Thai,6 weeks,6 weeks,Low,216,rectangle_java2.jpg,13,33212.721,2554.824692,107.542449

Ogama Analysis

Import data automatically into Ogama by manipulating the database

In [7]:
# Path to database
database_path = 'your-database-path.db'


drop_all_subject_tables_emip(database_path)

for i in range(1, 217):
	# If the file i+'_rawdata.tsv' exists
	filepath = 'data/emip_dataset/rawdata/'+ str(i) + '_rawdata.tsv'
	if os.path.isfile(filepath):
		# Import the data into the database
		import_data_into_ogama_emip(filepath, 'S' + str(i), database_path)
		print('Imported data for subject S' + str(i))

Exception: Database does not exist

Now enter Ogama, load the experiment that is using this database and run the fixation algorithm.

Import the fixations from the database and calculate our results

In [ ]:
import pandas as pd
import os


total_results = pd.DataFrame()

# Calculate the results for each subject
for i in range(1, 217):
	# If the folder i exists
	path = 'data/emip_dataset/rawdata/' + str(i) + '_rawdata.tsv'
	if os.path.isfile(path):
		# Append to the total_results dataframe
		total_results = pd.concat([total_results, calculate_results_for_subject_emip('S' + str(i), database_path)])


total_results['Subject'] = total_results['Subject'].str[1:].astype(int)
total_results = total_results.reset_index()

# Dictionary to map the TrialID to the corresponding task name
num_to_trial = {
    '1': 'mupliple_choice_rectangle.jpg',
    '2': 'mupliple_choice_vehicle.jpg',
    '3': 'rectangle_java.jpg',
    '4': 'rectangle_java2.jpg',
    '5': 'rectangle_python.jpg',
    '6': 'rectangle_scala.jpg',
    '7': 'vehicle_java.jpg',
    '8': 'vehicle_java2.jpg',
    '9': 'vehicle_python.jpg',
    '10': 'vehicle_scala.jpg',
}

# Change the TrialID to the corresponding task name
total_results['TrialID'] = total_results['TrialID'].astype(str)
total_results['TrialID'] = total_results['TrialID'].map(num_to_trial)

# Drop all colums where the TrialID contains 'mupliple_choice'
total_results = total_results[~total_results['TrialID'].str.contains('mupliple_choice')]

# We combine the two dataframes into one by combining the columns where the values of Participant and Task are the same
results_ogama = pd.merge(participants_metadata, total_results, how='inner', left_on=['id'], right_on=['Subject'])
# Rename the columns Fixation Count, Total Fixation Duration and Average Fixation Duration
results_ogama = results_ogama.rename(columns={
	'Total Fixation Count': 'Fixation Count', 
	'Total Fixation Duration': 'Total Fixation Duration [ms]', 
	'Average Fixation Duration': 'Average Fixation Duration [ms]',
	'TrialID': 'Task'
})

results_ogama

,id,age,gender,mother_tongue,english_level,visual_aid,makeup,experiment_language,expertise_experiment_language,time_experiment_language,...,stimulus_vehicle,mother_tongue_original,time_experiment_language_original,time_programming_original,other_languages_original,Task,Fixation Count,Total Fixation Duration [ms],Average Fixation Duration [ms],Subject
0,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,vehicle_java.jpg,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,rectangle_java.jpg,49,9865,201.326531,1
1,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,vehicle_java.jpg,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,vehicle_java.jpg,194,43131,222.324742,1
2,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,vehicle_java2.jpg,Slovak,2,5,"c++(low), php(medium), delphi(low)",rectangle_java2.jpg,151,35584,235.655629,2
3,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,vehicle_java2.jpg,Slovak,2,5,"c++(low), php(medium), delphi(low)",vehicle_java2.jpg,160,46040,287.750000,2
4,3,27,female,Hebrew,high,no,no,Java,none,0.0,...,vehicle_java2.jpg,Hebrew,0,0,c# (low),rectangle_java2.jpg,105,27686,263.676190,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,214,21,male,Slovak,high,no,no,Java,medium,1.0,...,vehicle_java2.jpg,Slovak,1,4,"C (medium) , JavaScript (medium)",vehicle_java2.jpg,405,99946,246.780247,214
409,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,vehicle_java2.jpg,slovak,1,2,C (medium) c# (medium) Java (medium),rectangle_java2.jpg,156,41962,268.987179,215
410,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,vehicle_java2.jpg,slovak,1,2,C (medium) c# (medium) Java (medium),vehicle_java2.jpg,230,63208,274.817391,215
411,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,vehicle_java2.jpg,Thai,6 weeks,6 weeks,Low,rectangle_java2.jpg,148,25092,169.540541,216
412,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,vehicle_java2.jpg,Thai,6 weeks,6 weeks,Low,vehicle_java2.jpg,307,56132,182.840391,216

Export the saccades from Ogama into the results folder with the name 'ogama_saccades_emip.txt'.

Then continue with the jupyter notebook.

In [ ]:
import pandas as pd

# Read the results from the file results/ogama_saccades_emip.txt
results_ogama_saccades_base = pd.read_csv('results/ogama_saccades_emip.txt', delimiter='\t', low_memory=False, on_bad_lines='skip', comment='#')

# Convert the SubjectName to an integer
results_ogama_saccades_base['SubjectName'] = results_ogama_saccades_base['SubjectName'].str[1:].astype(int)

# Drop all unnecessary columns
results_ogama_saccades_base = results_ogama_saccades_base[['SubjectName', 'Trial Name', 'CountInTrial', 'StartTime', 'Duration', 'Distance', 'Validity']]

# Convert all columns to the correct data type and format
results_ogama_saccades_base['Duration'] = results_ogama_saccades_base['Duration'].astype(str)
results_ogama_saccades_base['Duration'] = results_ogama_saccades_base['Duration'].str.replace(',', '.').astype(float)
results_ogama_saccades_base['Distance'] = results_ogama_saccades_base['Distance'].astype(str)
results_ogama_saccades_base['Distance'] = results_ogama_saccades_base['Distance'].str.replace(',', '.').astype(float)


grouped = results_ogama_saccades_base.groupby(['SubjectName', 'Trial Name'])

# Group the results by the participant and the task
results_ogama_saccades = grouped.agg({
    'Distance': 'mean',
    'Duration': 'mean',
    'CountInTrial': 'sum'
}).reset_index()

results_ogama_saccades.rename(columns={
    'Distance': 'Average Saccade Distance [px]',
    'Duration': 'Average Saccade Duration [ms]',
    'CountInTrial': 'TotalCountInTrial',
	'Trial Name': 'Task'
}, inplace=True)

# Drop all colums where the TrialID contains 'mupliple_choice'
results_ogama_saccades = results_ogama_saccades[~results_ogama_saccades['Task'].str.contains('mupliple_choice')]


# Combine the two dataframes into one by combining the columns where the values of Participant are the same
results_ogama_saccades = pd.merge(participants_metadata, results_ogama_saccades, how='inner', left_on=['id'], right_on=['SubjectName'])

results_ogama_saccades

,id,age,gender,mother_tongue,english_level,visual_aid,makeup,experiment_language,expertise_experiment_language,time_experiment_language,...,stimulus_vehicle,mother_tongue_original,time_experiment_language_original,time_programming_original,other_languages_original,SubjectName,Task,Average Saccade Distance [px],Average Saccade Duration [ms],TotalCountInTrial
0,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,vehicle_java.jpg,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,1,rectangle_java.jpg,138.137303,402.354167,1176
1,1,63,male,Czech,high,glasses,no,Java,high,30.0,...,vehicle_java.jpg,czech,30y,40+,CoffeeScript (high) JavaScript (high) Python (...,1,vehicle_java.jpg,116.809112,171.880829,18721
2,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,vehicle_java2.jpg,Slovak,2,5,"c++(low), php(medium), delphi(low)",2,rectangle_java2.jpg,89.623321,61.713333,11325
3,2,24,male,Slovak,medium,glasses,no,Java,medium,2.0,...,vehicle_java2.jpg,Slovak,2,5,"c++(low), php(medium), delphi(low)",2,vehicle_java2.jpg,91.482446,49.811321,12720
4,3,27,female,Hebrew,high,no,no,Java,none,0.0,...,vehicle_java2.jpg,Hebrew,0,0,c# (low),3,rectangle_java2.jpg,91.891677,30.913462,5460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
407,214,21,male,Slovak,high,no,no,Java,medium,1.0,...,vehicle_java2.jpg,Slovak,1,4,"C (medium) , JavaScript (medium)",214,vehicle_java2.jpg,106.649906,17.126238,81810
408,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,vehicle_java2.jpg,slovak,1,2,C (medium) c# (medium) Java (medium),215,rectangle_java2.jpg,107.206963,21.593548,12090
409,215,22,male,Slovak,medium,no,no,Java,medium,1.0,...,vehicle_java2.jpg,slovak,1,2,C (medium) c# (medium) Java (medium),215,vehicle_java2.jpg,138.203372,19.615721,26335
410,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,vehicle_java2.jpg,Thai,6 weeks,6 weeks,Low,216,rectangle_java2.jpg,105.042397,57.394558,10878
411,216,22,female,Thai,high,glasses,no,Java,none,0.0,...,vehicle_java2.jpg,Thai,6 weeks,6 weeks,Low,216,vehicle_java2.jpg,95.565078,58.830065,46971

In [ ]:

def adapt_results(results):
	# Map the data of expertise_experiment_language and expertise_programming to the following values: none = 0, low = 1, medium = 2, high = 3
	results['expertise_experiment_language'] = results['expertise_experiment_language'].map({'none': 0, 'low': 1, 'medium': 2, 'high': 3, 0: 0, 1: 1, 2: 2, 3: 3})
	results['expertise_programming'] = results['expertise_programming'].map({'none': 0, 'low': 1, 'medium': 2, 'high': 3, 0: 0, 1: 1, 2: 2, 3: 3})

	results.loc[results['time_programming'] == '40.0+', 'time_programming'] = 40.0
	results['time_programming'] = results['time_programming'].astype(float)

	return results


def show_results_tasks(results, results_saccades):
	
	results = adapt_results(results)
	results_saccades = adapt_results(results_saccades)
	
	results_mean_per_subject = results.groupby(['id']).mean(numeric_only=True)
	results_saccades_mean_per_subject = results_saccades.groupby(['id']).mean(numeric_only=True)

	# Vehicle Task performance

	results_vehicle = results[results['stimulus_vehicle'] == results['Task']]
	# Group the results by the id of the participant and calculate the mean of the Fixation Count and Total Fixation Duration
	results_vehicle_mean_per_subject = results_vehicle.groupby(['id']).mean(numeric_only=True)[["correct_vehicle", "Fixation Count", "Total Fixation Duration [ms]"]]

	spearman_vehicle_count = spearmanr(results_vehicle_mean_per_subject['Fixation Count'], results_vehicle_mean_per_subject['correct_vehicle'])

	spearman_vehicle_dur = spearmanr(results_vehicle_mean_per_subject['Total Fixation Duration [ms]'], results_vehicle_mean_per_subject['correct_vehicle'])

	results_saccades_vehicle = results_saccades[results_saccades['stimulus_vehicle'] == results_saccades['Task']]
	# Group the results by the id of the participant and calculate the mean of the Fixation Count and Total Fixation Duration
	results_saccades_vehicle_mean_per_subject = results_saccades_vehicle.groupby(['id']).mean(numeric_only=True)[["correct_vehicle", "Average Saccade Distance [px]", "Average Saccade Duration [ms]"]]

	spearman_saccades_vehicle_dist = spearmanr(results_saccades_vehicle_mean_per_subject['Average Saccade Distance [px]'], results_saccades_vehicle_mean_per_subject['correct_vehicle'])

	spearman_saccades_vehicle_dur = spearmanr(results_saccades_vehicle_mean_per_subject['Average Saccade Duration [ms]'], results_saccades_vehicle_mean_per_subject['correct_vehicle'])



	# Rectangle Task performance

	results_rectangle = results[results['stimulus_rectangle'] == results['Task']]
	# Group the results by the id of the participant and calculate the mean of the Fixation Count and Total Fixation Duration
	results_rectangle_mean_per_subject = results_rectangle.groupby(['id']).mean(numeric_only=True)[["correct_rectangle", "Fixation Count", "Total Fixation Duration [ms]"]]

	spearman_rectangle_count = spearmanr(results_rectangle_mean_per_subject['Fixation Count'], results_rectangle_mean_per_subject['correct_rectangle'])

	spearman_rectangle_dur = spearmanr(results_rectangle_mean_per_subject['Total Fixation Duration [ms]'], results_rectangle_mean_per_subject['correct_rectangle'])

	results_saccades_rectangle = results_saccades[results_saccades['stimulus_rectangle'] == results_saccades['Task']]
	# Group the results by the id of the participant and calculate the mean of the Fixation Count and Total Fixation Duration
	results_saccades_rectangle_mean_per_subject = results_saccades_rectangle.groupby(['id']).mean(numeric_only=True)[["correct_rectangle", "Average Saccade Distance [px]", "Average Saccade Duration [ms]"]]

	spearman_saccades_rectangle_dist = spearmanr(results_saccades_rectangle_mean_per_subject['Average Saccade Distance [px]'], results_saccades_rectangle_mean_per_subject['correct_rectangle'])

	spearman_saccades_rectangle_dur = spearmanr(results_saccades_rectangle_mean_per_subject['Average Saccade Duration [ms]'], results_saccades_rectangle_mean_per_subject['correct_rectangle'])




	# Self Eval Experiment language

	results_self_eval_exp = results_mean_per_subject[['expertise_experiment_language', 'Fixation Count', 'Total Fixation Duration [ms]']]
	spearman_self_eval_exp_count = spearmanr(results_self_eval_exp['Fixation Count'], results_self_eval_exp['expertise_experiment_language'])

	spearman_self_eval_exp_dur = spearmanr(results_self_eval_exp['Total Fixation Duration [ms]'], results_self_eval_exp['expertise_experiment_language'])

	results_saccades_self_eval_exp = results_saccades_mean_per_subject[['expertise_experiment_language', 'Average Saccade Distance [px]', 'Average Saccade Duration [ms]']]

	spearman_saccades_self_eval_exp_dist = spearmanr(results_saccades_self_eval_exp['Average Saccade Distance [px]'], results_self_eval_exp['expertise_experiment_language'])




	# Self Eval Programming language

	results_self_eval_prog = results_mean_per_subject[['expertise_programming', 'Fixation Count', 'Total Fixation Duration [ms]']]
	spearman_self_eval_prog_count = spearmanr(results_self_eval_prog['Fixation Count'], results_self_eval_prog['expertise_programming'])
	spearman_self_eval_prog_dur = spearmanr(results_self_eval_prog['Total Fixation Duration [ms]'], results_self_eval_prog['expertise_programming'])

	results_saccades_self_eval_prog = results_saccades_mean_per_subject[['expertise_programming', 'Average Saccade Distance [px]', 'Average Saccade Duration [ms]']]
	spearman_saccades_self_eval_prog_dist = spearmanr(results_saccades_self_eval_prog['Average Saccade Distance [px]'], results_self_eval_prog['expertise_programming'])
	spearman_saccades_self_eval_prog_dur = spearmanr(results_saccades_self_eval_prog['Average Saccade Duration [ms]'], results_self_eval_prog['expertise_programming'])



	# Time Experiment language

	results_time_exp = results_mean_per_subject[['time_experiment_language', 'Fixation Count', 'Total Fixation Duration [ms]']]
	spearman_time_exp_count = spearmanr(results_time_exp['Fixation Count'], results_time_exp['time_experiment_language'])
	spearman_time_exp_dur = spearmanr(results_time_exp['Total Fixation Duration [ms]'], results_time_exp['time_experiment_language'])

	results_saccades_time_exp = results_saccades_mean_per_subject[['time_experiment_language', 'Average Saccade Distance [px]', 'Average Saccade Duration [ms]']]
	spearman_saccades_time_exp_dist = spearmanr(results_saccades_time_exp['Average Saccade Distance [px]'], results_time_exp['time_experiment_language'])
	spearman_saccades_time_exp_dur = spearmanr(results_saccades_time_exp['Average Saccade Duration [ms]'], results_time_exp['time_experiment_language'])



	# Time Programming language

	results_time_prog = results.groupby(['id']).mean(numeric_only=True)[['time_programming', 'Fixation Count', 'Total Fixation Duration [ms]']]
	spearman_time_prog_count = spearmanr(results_time_prog['Fixation Count'], results_time_prog['time_programming'])
	spearman_time_prog_dur = spearmanr(results_time_prog['Total Fixation Duration [ms]'], results_time_prog['time_programming'])

	results_saccades_time_prog = results_saccades_mean_per_subject[['time_programming', 'Average Saccade Distance [px]', 'Average Saccade Duration [ms]']]
	spearman_saccades_time_prog_dist = spearmanr(results_saccades_time_prog['Average Saccade Distance [px]'], results_time_prog['time_programming'])
	spearman_saccades_time_prog_dur = spearmanr(results_saccades_time_prog['Average Saccade Duration [ms]'], results_time_prog['time_programming'])


	# We create a table to show the results

	data = [
		[
			'Vehicle Task', 
			'%.4f' % spearman_vehicle_count.correlation,
			'%.4f' % spearman_vehicle_dur.correlation,
			'%.4f' % spearman_saccades_vehicle_dist.correlation,
			'%.4f' % spearman_saccades_vehicle_dur.correlation
		],
		[
			'Rectangle Task', 
			'%.4f' % spearman_rectangle_count.correlation,
			'%.4f' % spearman_rectangle_dur.correlation,
			'%.4f' % spearman_saccades_rectangle_dist.correlation,
			'%.4f' % spearman_saccades_rectangle_dur.correlation
		],
		[
			'Self Eval Experiment Language', 
			'%.4f' % spearman_self_eval_exp_count.correlation,
			'%.4f' % spearman_self_eval_exp_dur.correlation,
			'%.4f' % spearman_saccades_self_eval_exp_dist.correlation,
			'%.4f' % spearman_saccades_self_eval_exp_dist.correlation
		],
		[
			'Self Eval Programming Language', 
			'%.4f' % spearman_self_eval_prog_count.correlation,
			'%.4f' % spearman_self_eval_prog_dur.correlation,
			'%.4f' % spearman_saccades_self_eval_prog_dist.correlation,
			'%.4f' % spearman_saccades_self_eval_prog_dur.correlation
		],
		[
			'Time Experiment Language', 
			'%.4f' % spearman_time_exp_count.correlation,
			'%.4f' % spearman_time_exp_dur.correlation,
			'%.4f' % spearman_saccades_time_exp_dist.correlation,
			'%.4f' % spearman_saccades_time_exp_dur.correlation
		],
		[
			'Time Programming Language', 
			'%.4f' % spearman_time_prog_count.correlation,
			'%.4f' % spearman_time_prog_dur.correlation,
			'%.4f' % spearman_saccades_time_prog_dist.correlation,
			'%.4f' % spearman_saccades_time_prog_dur.correlation
		]
	]


	data_df = pd.DataFrame(data)
	data_df.columns = ['', 'Number of Fixations', 'Sum of Fixation Duration', 'Saccade Length', 'Saccade Duration']
	return data_df

In [ ]:
from scipy.stats import wilcoxon
from scipy.stats import mannwhitneyu
from scipy.stats import spearmanr
import numpy

def adapt_results(results):
	# Change the type of the column time_programming to float
	results.loc[results['time_programming'] == '40.0+', 'time_programming'] = 40.0
	results['time_programming'] = results['time_programming'].astype(float)
	# We group the data by time_programming with either between 0.5 and 4 and 4+ and dispose of those with less than 0.5
	results = results[results['time_programming'] >= 0.5]

	# Remove NaN values
	results = results.dropna(subset=['time_programming'])

	# Add a new column time_programming_grouped that groups the time_programming into two groups: 0 = 0.5-4 and 1 = 4+
	results['time_programming_grouped'] = pd.cut(results['time_programming'], [0.5, 4, 40], labels=['0', '1'])
	results = results.dropna(subset=['time_programming_grouped'])
	results['time_programming_grouped'] = results['time_programming_grouped'].astype(int)
	return results



def show_results_expertise(results, results_saccades):
	results = adapt_results(results)
	results_saccades = adapt_results(results_saccades)

	# Number of fixations
	results_fixations_count_novices = results[results['time_programming_grouped'] == 0].groupby(['id'])['Fixation Count'].sum()
	results_mean_fixations_count_novices = results_fixations_count_novices.mean()
	results_std_fixations_count_novices = results_fixations_count_novices.std()

	results_fixations_count_experts = results[results['time_programming_grouped'] == 1].groupby(['id'])['Fixation Count'].sum()
	results_mean_fixations_count_experts = results_fixations_count_experts.mean()
	results_std_fixations_count_experts = results_fixations_count_experts.std()

	
	
	# Total fixation duration
	results_fixations_dur_novices = results[results['time_programming_grouped'] == 0].groupby(['id'])['Total Fixation Duration [ms]'].sum()
	results_mean_fixations_dur_novices = results_fixations_dur_novices.mean()
	results_std_fixations_dur_novices = results_fixations_dur_novices.std()

	results_fixations_dur_experts = results[results['time_programming_grouped'] == 1].groupby(['id'])['Total Fixation Duration [ms]'].sum()
	results_mean_fixations_dur_experts = results_fixations_dur_experts.mean()
	results_std_fixations_dur_experts = results_fixations_dur_experts.std()



	# Saccade length
	results_saccades_dist_novices = results_saccades[results_saccades['time_programming_grouped'] == 0].groupby(['id'])['Average Saccade Distance [px]'].sum()
	results_mean_saccades_dist_novices = results_saccades_dist_novices.mean()
	results_std_saccades_dist_novices = results_saccades_dist_novices.std()

	results_saccades_dist_experts = results_saccades[results_saccades['time_programming_grouped'] == 1].groupby(['id'])['Average Saccade Distance [px]'].sum()
	results_mean_saccades_dist_experts = results_saccades_dist_experts.mean()
	results_std_saccades_dist_experts = results_saccades_dist_experts.std()


	# Saccade duration
	results_saccades_dur_novices = results_saccades[results_saccades['time_programming_grouped'] == 0].groupby(['id'])['Average Saccade Duration [ms]'].sum()
	results_mean_saccades_dur_novices = results_saccades_dur_novices.mean()
	results_std_saccades_dur_novices = results_saccades_dur_novices.std()

	results_saccades_dur_experts = results_saccades[results_saccades['time_programming_grouped'] == 1].groupby(['id'])['Average Saccade Duration [ms]'].sum()
	results_mean_saccades_dur_experts = results_saccades_dur_experts.mean()
	results_std_saccades_dur_experts = results_saccades_dur_experts.std()





	# We create a table to show the results

	data = [
		[
			'Number of Fixations', 
			'Experts',
			'%.2f' % results_mean_fixations_count_experts,
			'%.2f' % results_std_fixations_count_experts
		],
		[
			'Number of Fixations', 
			'Novices',
			'%.2f' % results_mean_fixations_count_novices,
			'%.2f' % results_std_fixations_count_novices
		],
		[
			'Total Fixation Duration [ms]', 
			'Experts',
			'%.2f' % results_mean_fixations_dur_experts,
			'%.2f' % results_std_fixations_dur_experts
		],
		[
			'Total Fixation Duration [ms]', 
			'Novices',
			'%.2f' % results_mean_fixations_dur_novices,
			'%.2f' % results_std_fixations_dur_novices
		],
		[
			'Saccade Length', 
			'Experts',
			'%.2f' % results_mean_saccades_dist_experts,
			'%.2f' % results_std_saccades_dist_experts
		],
		[
			'Saccade Length', 
			'Novices',
			'%.2f' % results_mean_saccades_dist_novices,
			'%.2f' % results_std_saccades_dist_novices
		],
		[
			'Saccade Duration', 
			'Experts',
			'%.2f' % results_mean_saccades_dur_experts,
			'%.2f' % results_std_saccades_dur_experts
		],
		[
			'Saccade Duration', 
			'Novices',
			'%.2f' % results_mean_saccades_dur_novices,
			'%.2f' % results_std_saccades_dur_novices
		]

	]

	data_df = pd.DataFrame(data)
	data_df.columns = ['Eye Movement Measure', 'Level of expertise', 'Average of actual data', 'SD']
	return data_df

In [ ]:
def adapt_results(results):
	# Change the type of the column time_programming to float
	results.loc[results['time_programming'] == '40.0+', 'time_programming'] = 40.0
	results['time_programming'] = results['time_programming'].astype(float)
	# We group the data by time_programming with either between 0.5 and 4 and 4+ and dispose of those with less than 0.5
	results = results[results['time_programming'] >= 0.5]

	# Remove NaN values
	results = results.dropna(subset=['time_programming'])

	# Add a new column time_programming_grouped that groups the time_programming into two groups: 0 = 0.5-4 and 1 = 4+
	results['time_programming_grouped'] = pd.cut(results['time_programming'], [0.5, 4, 40], labels=['0', '1'])
	results = results.dropna(subset=['time_programming_grouped'])
	results['time_programming_grouped'] = results['time_programming_grouped'].astype(int)
	return results

def cohend(d1: Series, d2: Series) -> float:

    # calculate the size of samples
    n1, n2 = len(d1), len(d2)

    # calculate the variance of the samples
    s1, s2 = var(d1, ddof=1), var(d2, ddof=1)

    # calculate the pooled standard deviation
    s = sqrt(((n1 - 1) * s1 + (n2 - 1) * s2) / (n1 + n2 - 2))

    # calculate the means of the samples
    u1, u2 = mean(d1), mean(d2)

    # return the effect size
    return (u1 - u2) / s

def mannwhitney_z(U, nx, ny):
	return (U - (nx * ny / 2)) / sqrt(nx * ny * (nx + ny + 1) / 12)


def get_results(x, y):
	nx = len(x)
	ny = len(y)
	U1, p = mannwhitneyu(x, y)
	U2 = nx * ny - U1
	U = min(U1, U2)
	z = mannwhitney_z(U, nx, ny)
	cohend_value = cohend(x, y)
	return U, p, z, cohend_value


def show_results_expertise_significance(results, results_saccades):
	results = adapt_results(results)
	results_saccades = adapt_results(results_saccades)


	mannwhitneyu_fixations_count = get_results(results[results['time_programming_grouped'] == 0]['Fixation Count'], results[results['time_programming_grouped'] == 1]['Fixation Count'])

	mannwhitneyu_fixations_dur = get_results(results[results['time_programming_grouped'] == 0]['Total Fixation Duration [ms]'], results[results['time_programming_grouped'] == 1]['Total Fixation Duration [ms]'])

	mannwhitneyu_saccades_dist = get_results(results_saccades[results_saccades['time_programming_grouped'] == 0]['Average Saccade Distance [px]'], results_saccades[results_saccades['time_programming_grouped'] == 1]['Average Saccade Distance [px]'])

	mannwhitneyu_saccades_dur = get_results(results_saccades[results_saccades['time_programming_grouped'] == 0]['Average Saccade Duration [ms]'], results_saccades[results_saccades['time_programming_grouped'] == 1]['Average Saccade Duration [ms]'])

	# We create a table to show the results
	data = [
		[
			'Number of Fixations', 
			'%.4f' % mannwhitneyu_fixations_count[0],
			'%.4f' % mannwhitneyu_fixations_count[1],
			'%.4f' % mannwhitneyu_fixations_count[2],
			'%.4f' % mannwhitneyu_fixations_count[3]
		],
		[
			'Total Fixation Duration [ms]', 
			'%.4f' % mannwhitneyu_fixations_dur[0],
			'%.4f' % mannwhitneyu_fixations_dur[1],
			'%.4f' % mannwhitneyu_fixations_dur[2],
			'%.4f' % mannwhitneyu_fixations_dur[3]
		],
		[
			'Saccade Length', 
			'%.4f' % mannwhitneyu_saccades_dist[0],
			'%.4f' % mannwhitneyu_saccades_dist[1],
			'%.4f' % mannwhitneyu_saccades_dist[2],
			'%.4f' % mannwhitneyu_saccades_dist[3]
		],
		[
			'Saccade Duration', 
			'%.4f' % mannwhitneyu_saccades_dur[0],
			'%.4f' % mannwhitneyu_saccades_dur[1],
			'%.4f' % mannwhitneyu_saccades_dur[2],
			'%.4f' % mannwhitneyu_saccades_dur[3]
		]
	]

	data_df = pd.DataFrame(data)
	data_df.columns = ['Eye Movement Feature', 'U', 'p', 'Z', 'Cohen\'s d']
	return data_df

In [ ]:
show_results_tasks(results_pygaze, results_pygaze_saccades)

,,Number of Fixations,Sum of Fixation Duration,Saccade Length,Saccade Duration
0,Vehicle Task,-0.0122,-0.0077,0.0096,0.0114
1,Rectangle Task,0.0978,0.1546,-0.0155,-0.0100
2,Self Eval Experiment Language,0.1151,0.1177,0.0385,0.0385
3,Self Eval Programming Language,0.0556,0.0630,0.0188,0.0186
4,Time Experiment Language,0.0489,0.0647,-0.0330,-0.0259
5,Time Programming Language,-0.0251,0.0218,-0.1413,-0.1111

In [ ]:
show_results_tasks(results_ogama, results_ogama_saccades)

,,Number of Fixations,Sum of Fixation Duration,Saccade Length,Saccade Duration
0,Vehicle Task,-0.0016,-0.0158,0.0129,0.0388
1,Rectangle Task,0.0949,0.1378,0.0691,-0.0278
2,Self Eval Experiment Language,0.0918,0.1124,0.1139,0.1139
3,Self Eval Programming Language,0.0540,0.0760,-0.0221,-0.0005
4,Time Experiment Language,0.0317,0.0578,0.0869,-0.0003
5,Time Programming Language,-0.0239,0.0137,-0.0609,-0.0692

![Results Study EMIP](images/results_study_emip.png)

In [ ]:
show_results_expertise(results_pygaze, results_pygaze_saccades)

,Eye Movement Measure,Level of expertise,Average of actual data,SD
0,Number of Fixations,Experts,463.15,238.25
1,Number of Fixations,Novices,532.65,238.31
2,Total Fixation Duration [ms],Experts,82436.41,46433.59
3,Total Fixation Duration [ms],Novices,88930.49,41845.98
4,Saccade Length,Experts,234.49,105.34
5,Saccade Length,Novices,262.03,94.71
6,Saccade Duration,Experts,2921.30,6136.59
7,Saccade Duration,Novices,3196.81,5092.05

In [ ]:
show_results_expertise(results_ogama, results_ogama_saccades)

,Eye Movement Measure,Level of expertise,Average of actual data,SD
0,Number of Fixations,Experts,343.20,172.36
1,Number of Fixations,Novices,409.69,176.89
2,Total Fixation Duration [ms],Experts,95178.89,49056.95
3,Total Fixation Duration [ms],Novices,107707.32,44258.42
4,Saccade Length,Experts,225.38,49.33
5,Saccade Length,Novices,231.39,40.81
6,Saccade Duration,Experts,135.84,352.29
7,Saccade Duration,Novices,256.42,644.82

![Results Study EMIP 2](images/results_study_emip_2.png)

In [ ]:
show_results_expertise_significance(results_pygaze, results_pygaze_saccades)

           Eye Movement Feature           U       p        Z Cohen's D
0           Number of Fixations  14182.5000  0.0042  -2.8616    0.2486
1  Total Fixation Duration [ms]  15278.0000  0.0719  -1.8002    0.1267
2                Saccade Length  13680.0000  0.0008  -3.3484    0.2439
3              Saccade Duration  14199.0000  0.0044  -2.8456    0.0404

In [ ]:
show_results_expertise_significance(results_ogama, results_ogama_saccades)

           Eye Movement Feature           U       p        Z Cohen's D
0           Number of Fixations  13401.0000  0.0003  -3.6187    0.3193
1  Total Fixation Duration [ms]  14038.0000  0.0027  -3.0016    0.2266
2                Saccade Length  15191.0000  0.0596  -1.8845    0.1125
3              Saccade Duration  15585.5000  0.1332  -1.5022    0.1855

![Results Study EMIP 3](images/results_study_emip_3.png)

Comparison between differently chosen parameters

In [ ]:
def load_results(name):

	# We load the PyGazeAnalyzer results
	res = pd.read_csv(f'results/{name}.csv')

	# Drop all colums where the task contains 'mupliple_choice'
	res = res[~res['Task'].str.contains('mupliple_choice')]

	# We combine the two dataframes into one by combining the columns where the values of Participant are the same
	res = pd.merge(participants_metadata, res, how='inner', left_on=['id'], right_on=['Participant'])

	return res

pygaze_fixations_emip_dataset_lower_maxdist1 = load_results('pygaze_fixations_emip_dataset_lower_maxdist1')
pygaze_fixations_emip_dataset_lower_maxdist2 = load_results('pygaze_fixations_emip_dataset_lower_maxdist2')

pygaze_fixations_emip_dataset_higher_maxdist1 = load_results('pygaze_fixations_emip_dataset_higher_maxdist1')
pygaze_fixations_emip_dataset_higher_maxdist2 = load_results('pygaze_fixations_emip_dataset_higher_maxdist2')

pygaze_fixations_emip_dataset_lower_mindur1 = load_results('pygaze_fixations_emip_dataset_lower_mindur1')
pygaze_fixations_emip_dataset_lower_mindur2 = load_results('pygaze_fixations_emip_dataset_lower_mindur2')

pygaze_fixations_emip_dataset_higher_mindur1 = load_results('pygaze_fixations_emip_dataset_higher_mindur1')
pygaze_fixations_emip_dataset_higher_mindur2 = load_results('pygaze_fixations_emip_dataset_higher_mindur2')

In [ ]:
def show_results_tasks_fixations(fixations):
	res = show_results_tasks(fixations, results_pygaze_saccades)
	# Remove the columns 'Saccade Length' and 'Saccade Duration'
	res = res.drop(columns=['Saccade Length', 'Saccade Duration'])
	return res

In [ ]:
def show_results_expertise_fixations(fixations):
	res = show_results_expertise(fixations, results_pygaze_saccades)
	# Remove the rows 4-7 as those don't change
	res = res.drop([4, 5, 6, 7])
	return res

In [ ]:
def show_results_expertise_significance_fixations(fixations):
	res = show_results_expertise_significance(fixations, results_pygaze_saccades)
	# Remove the rows 2 and 3 as those don't change
	res = res.drop([2, 3])
	return res

In [ ]:
show_results_tasks_fixations(pygaze_fixations_emip_dataset_lower_maxdist1)

                                  Number of Fixations Sum of Fixation Duration
0                    Vehicle Task             -0.0070                   0.0031
1                  Rectangle Task              0.1365                   0.1641
2   Self Eval Experiment Language              0.1144                   0.1086
3  Self Eval Programming Language              0.0571                   0.0579
4        Time Experiment Language              0.0620                   0.0632
5       Time Programming Language              0.0117                   0.0419

In [ ]:
show_results_tasks_fixations(pygaze_fixations_emip_dataset_lower_maxdist2)

                                  Number of Fixations Sum of Fixation Duration
0                    Vehicle Task              0.0075                   0.0125
1                  Rectangle Task              0.1447                   0.1687
2   Self Eval Experiment Language              0.0995                   0.0938
3  Self Eval Programming Language              0.0604                   0.0664
4        Time Experiment Language              0.0500                   0.0583
5       Time Programming Language              0.0398                   0.0759

In [ ]:
show_results_tasks_fixations(pygaze_fixations_emip_dataset_higher_maxdist1)

                                  Number of Fixations Sum of Fixation Duration
0                    Vehicle Task             -0.0094                  -0.0124
1                  Rectangle Task              0.0752                   0.1417
2   Self Eval Experiment Language              0.1144                   0.1195
3  Self Eval Programming Language              0.0494                   0.0636
4        Time Experiment Language              0.0435                   0.0670
5       Time Programming Language             -0.0406                   0.0139

In [ ]:
show_results_tasks_fixations(pygaze_fixations_emip_dataset_higher_maxdist2)

                                  Number of Fixations Sum of Fixation Duration
0                    Vehicle Task             -0.0154                  -0.0199
1                  Rectangle Task              0.0676                   0.1330
2   Self Eval Experiment Language              0.1242                   0.1215
3  Self Eval Programming Language              0.0424                   0.0567
4        Time Experiment Language              0.0417                   0.0622
5       Time Programming Language             -0.0616                  -0.0024

In [ ]:
show_results_expertise_fixations(pygaze_fixations_emip_dataset_lower_maxdist1)

,Eye Movement Measure,Level of expertise,Average of actual data,SD
0,Number of Fixations,Experts,511.93,294.09
1,Number of Fixations,Novices,563.55,273.25
2,Total Fixation Duration [ms],Experts,67396.24,41398.48
3,Total Fixation Duration [ms],Novices,70276.74,36565.81

In [ ]:
show_results_expertise_fixations(pygaze_fixations_emip_dataset_lower_maxdist2)

,Eye Movement Measure,Level of expertise,Average of actual data,SD
0,Number of Fixations,Experts,475.15,298.51
1,Number of Fixations,Novices,498.10,270.84
2,Total Fixation Duration [ms],Experts,50305.62,34347.24
3,Total Fixation Duration [ms],Novices,50162.88,29808.01

In [ ]:
show_results_expertise_significance_fixations(pygaze_fixations_emip_dataset_lower_maxdist1)

           Eye Movement Feature           U       p        Z Cohen's D
0           Number of Fixations  15091.0000  0.0476  -1.9813    0.1579
1  Total Fixation Duration [ms]  15972.0000  0.2596  -1.1278    0.0643

In [ ]:
show_results_expertise_significance_fixations(pygaze_fixations_emip_dataset_lower_maxdist2)

           Eye Movement Feature           U       p        Z Cohen's D
0           Number of Fixations  15982.5000  0.2639  -1.1176    0.0704
1  Total Fixation Duration [ms]  16793.0000  0.7400  -0.3323   -0.0039

In [ ]:
show_results_expertise_significance_fixations(pygaze_fixations_emip_dataset_higher_maxdist1)

           Eye Movement Feature           U       p        Z Cohen's D
0           Number of Fixations  13620.0000  0.0007  -3.4066    0.3043
1  Total Fixation Duration [ms]  14951.0000  0.0343  -2.1170    0.1570

In [ ]:
show_results_expertise_significance_fixations(pygaze_fixations_emip_dataset_higher_maxdist2)

           Eye Movement Feature           U       p        Z Cohen's D
0           Number of Fixations  13289.5000  0.0002  -3.7268    0.3475
1  Total Fixation Duration [ms]  14634.0000  0.0154  -2.4241    0.1850